- name: Create Instances
  hosts: localhost
  roles:
    - create-instances

- name: Install MySQL
  hosts: private_instance
  vars:
    ansible_python_interpreter: /usr/bin/python
    ansible_ssh_common_args: "-o ProxyCommand='ssh -i {{ playbook_dir }}/{{ key_name }}.pem -W %h:%p -q ubuntu@{{ hostvars['localhost']['owncloud_public_ip'] }}'"
  roles:
    - install_mysql

- name: Install ownCloud
  hosts: ownCloud_instance
  roles:
    - install-ownCloud
