---
# tasks file for install-ownCloud

- debug: var=inventory_hostname
- debug: msg="{{ hostvars['localhost']['mysql_host']}}"

- set_fact:
    mysql_host: "{{ hostvars['localhost']['mysql_host']}}"

- name: Update repositories
  apt:
    update_cache: yes
  become: yes

- name: Install LAMP and other dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - apache2
      - php
      - libapache2-mod-php
      - php-mysql
      - curl
      - python3-pip
  become: yes

- name: Install pyOpenSSL
  pip:
    name: pyOpenSSL
  become: yes

- name: Edit Apache Config file
  shell: sed -i 's/DirectoryIndex index\.html index\.cgi index\.pl index\.php index\.xhtml index\.htm/DirectoryIndex index\.php index\.html index\.cgi index\.pl index\.xhtml index\.htm/g' /etc/apache2/mods-enabled/dir.conf
  become: yes

- name: Add ownCloud APT keys
  shell: curl https://download.owncloud.org/download/repositories/10.0/Ubuntu_18.04/Release.key | sudo apt-key add -
  become: yes

- name: Add owncloud to sources.list
  shell: echo 'deb http://download.owncloud.org/download/repositories/10.0/Ubuntu_18.04/ /' | sudo tee /etc/apt/sources.list.d/owncloud.list
  become: yes

- name: Update cache
  apt:
    update_cache: yes
  become: yes
  become_method: sudo

- name: Install owncloud and php mods
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - php-bz2
      - php-curl
      - php-gd
      - php-imagick
      - php-intl
      - php-mbstring
      - php-xml
      - php-zip
      - owncloud-files
  become: yes

- name: Enable pdo_mysql
  shell: phpenmod pdo_mysql
  become: yes

- name: Generate OpenSSL private key
  openssl_privatekey:
    path: /etc/ssl/private/apache-selfsigned.key
  become: yes

- name: Generate OpenSSL CSR
  openssl_csr:
    path: /etc/ssl/apache-selfsigned.csr
    privatekey_path: /etc/ssl/private/apache-selfsigned.key
    common_name: "{{ inventory_hostname }}"
  become: yes

- name: Generate Certificate for OpenSSL
  openssl_certificate:
    path: /etc/ssl/certs/apache-selfsigned.crt
    privatekey_path: /etc/ssl/private/apache-selfsigned.key
    csr_path: /etc/ssl/apache-selfsigned.csr
    provider: selfsigned
  become: yes

- name: Configure Apache
  copy:
    content: |
      SSLCipherSuite EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH
      SSLProtocol All -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
      SSLHonorCipherOrder On
      # Disable preloading HSTS for now.  You can use the commented out header line that includes
      # the "preload" directive if you understand the implications.
      # Header always set Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"
      Header always set X-Frame-Options DENY
      Header always set X-Content-Type-Options nosniff
      # Requires Apache >= 2.4
      SSLCompression off
      SSLUseStapling on
      SSLStaplingCache "shmcb:logs/stapling-cache(150000)"
      # Requires Apache >= 2.4.11
      SSLSessionTickets Off
    dest: /etc/apache2/conf-available/ssl-params.conf
    force: no
  become: yes

- name: Configure Apache Step 2
  replace:
    path: /etc/apache2/sites-available/default-ssl.conf
    regexp: 'DocumentRoot\s\/var\/www\/html'
    replace: 'DocumentRoot /var/www/owncloud'
  become: yes

- name: Configure Apache Step 3
  shell: sed -i 's\ServerAdmin webmaster@localhost\ServerAdmin danieb1996@live.com\g' /etc/apache2/sites-available/default-ssl.conf
  become: yes

- name: Configure Apache Step 4
  lineinfile:
    path: /etc/apache2/sites-available/default-ssl.conf
    insertafter: 'ServerAdmin danieb1996@live.com'
    line: '   ServerName {{ inventory_hostname }}'
    state: present
  become: yes

- name: Configure Apache Step 5
  lineinfile:
    path: /etc/apache2/sites-available/000-default.conf
    insertafter: 'ServerAdmin webmaster@localhost'
    line: 'Redirect permanent "/" "https://{{ inventory_hostname }}/"'
    state: present
  become: yes

- name: Configure Apache Step 6
  replace:
    path: /etc/apache2/sites-available/default-ssl.conf
    regexp: 'SSLCertificateFile\t\/etc\/ssl\/certs\/ssl\-cert\-snakeoil\.pem'
    replace: 'SSLCertificateFile      /etc/ssl/certs/apache-selfsigned.crt'
  become: yes

- name: Configure Apache Step 7
  replace:
    path: /etc/apache2/sites-available/default-ssl.conf
    regexp: 'SSLCertificateKeyFile\s+(.*)$'
    replace: 'SSLCertificateKeyFile      /etc/ssl/private/apache-selfsigned.key'
  become: yes

- name: Configure Apache Step 8
  lineinfile:
    path: /etc/apache2/sites-available/default-ssl.conf
    insertbefore: '</VirtualHost>'
    line: |
      BrowserMatch "MSIE [2-6]" \
                    nokeepalive ssl-unclean-shutdown \
                    downgrade-1.0 force-response-1.0
    state: present
  become: yes

- name: ufw settings
  shell: ufw allow 'Apache Full' && ufw delete allow 'Apache'
  become: yes

- name: Enabling Apache2 Modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - ssl
    - headers
  become: yes

- name: Enabling SSL VirtualHost
  shell: a2ensite default-ssl
  become: yes

- name: Enabling SSL params
  shell: a2enconf ssl-params
  become: yes

- name: ownCloud Config
  copy:
    content: |
      <?php
      $CONFIG = array (
        'trusted_domains' => 
        array (
          0 => '10.0.2.6',
        ),
        'datadirectory' => '/var/www/owncloud/data',
        'dbtype' => 'mysql',
        'dbname' => 'owncloud',
        'dbhost' => "{{ mysql_host }}",
        'version' => '10.1.0.4',
        'mysql.utf8mb4' => true,
        'dbuser' => 'owncloud',
        'dbpassword' => "{{ db_password }}",
        'logtimezone' => 'UTC',
        'installed' => true,
      );
    dest: /var/www/owncloud/config/config.php
    force: no
  become: yes

- name: Change config file permissions
  file:
    path: /var/www/owncloud/config/config.php
    owner: www-data
    group: www-data
    mode: 0640
  become: yes

- name: Restart Apache2
  service:
    name: apache2
    state: restarted
  become: yes

- name: Copying private key
  copy:
    src: "{{ playbook_dir }}/{{ key_file}}.pem"
    dest: /home/ubuntu
    mode: 0400