---
# tasks file for install-ownCloud

- debug: var=inventory_hostname
- debug: msg="{{ hostvars['localhost']['mysql_host']}}"

- set_fact:
    mysql_host: "{{ hostvars['localhost']['mysql_host']}}"

- name: Add PPA
  shell: add-apt-repository ppa:ondrej/php
  become: yes

- name: Update repositories
  apt:
    update_cache: yes
  become: yes

- name: Install LAMP and other dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - apache2
      - software-properties-common
      - libapache2-mod-php
      - curl
      - python3-pip
      - php7.1
  become: yes

- name: Install pyOpenSSL
  pip:
    name: pyOpenSSL
  become: yes

- name: Edit Apache Config file
  shell: sed -i 's/DirectoryIndex index\.html index\.cgi index\.pl index\.php index\.xhtml index\.htm/DirectoryIndex index\.php index\.html index\.cgi index\.pl index\.xhtml index\.htm/g' /etc/apache2/mods-enabled/dir.conf
  become: yes

- name: Add ownCloud APT keys
  shell: curl https://download.owncloud.org/download/repositories/production/Ubuntu_18.04/Release.key | sudo apt-key add -
  become: yes

- name: Add owncloud to sources.list
  shell: echo 'deb http://download.owncloud.org/download/repositories/production/Ubuntu_18.04/ /' | sudo tee /etc/apt/sources.list.d/owncloud.list
  become: yes

- name: Update cache
  apt:
    update_cache: yes
  become: yes
  become_method: sudo

- name: Install owncloud and php mods
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - php7.1-bz2
      - php7.1-mysql
      - php7.1-curl
      - php7.1-gd
      - php7.1-imagick
      - php7.1-intl
      - php7.1-mbstring
      - php7.1-xml
      - php7.1-zip
      - owncloud-files
  become: yes

- name: Enable pdo_mysql
  shell: phpenmod pdo_mysql
  become: yes

- name: Configure Apache
  replace:
    path: /etc/apache2/sites-enabled/000-default.conf
    regexp: 'DocumentRoot\s\/var\/www\/html'
    replace: 'DocumentRoot /var/www/owncloud'
  become: yes

- name: ufw settings
  shell: ufw allow 'Apache Full' && ufw delete allow 'Apache'
  become: yes

- name: Restart Apache2
  service:
    name: apache2
    state: restarted
  become: yes

- name: Copying private key
  copy:
    src: "{{ playbook_dir }}/{{ key_name }}.pem"
    dest: /home/ubuntu
    mode: 0400
