---
# vars file for instance_creation

region: us-east-1

group_name: Mongo Server Security Group
rules:
  - proto: tcp
    cidr_ip: 0.0.0.0/0
    ports:
      - 22
      - 27017
rules_egress:
  - proto: all
    cidr_ip: 0.0.0.0/0

instance_type: t2.micro
image: ami-0a313d6098716f372 # Ubuntu 18.04 x64
keypair: restserv 
count: 1
instance_tags:
  - Name: Mongo Server