---
# tasks file for win_instance

- name: create new key pair
  ec2_key:
    name: keypair1
    region: "{{ region }}"
  register: key

- name: save pem file
  copy:
    content: "{{ key.key.private_key }}"
    dest: keypair.pem
    mode: 0400

- name: create vpc 
  ec2_vpc_net:
    name: myvpc
    state: present
    cidr_block: 10.10.0.0/16
    region: "{{ region }}"
  register: vpc

- name: create internet gateway
  ec2_vpc_igw:
    tags:
      Name: my_igw
    vpc_id: "{{ vpc.vpc.id }}"
    state: present
    region: "{{ region }}"
  register: igw

- name: subnet
  ec2_vpc_subnet:
    tags:
      Name: my_subnet
    state: present
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ region }}"
    cidr: 10.10.0.0/24
  with_items: vpc
  register: vpc_subnet

- name: route table
  ec2_vpc_route_table:
    tags:
      Name: Public
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ region }}"
    subnets:
      - "{{ vpc_subnet.results[0].subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"
  register: route_table

- name: ec2 security group
  ec2_group:
    name: "{{ group_name }}"
    description: security group for Mongo server
    region: "{{ region }}"
    vpc_id: "{{ vpc.vpc.id }}"
    rules: "{{ rules }}"
    rules_egress: "{{ rules_egress }}"

- ec2:
    key_name: keypair1
    region: "{{ region }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    wait: yes
    group: "{{ group_name }}"
    count: 1
    vpc_subnet_id: "{{ vpc_subnet.results[0].subnet.id }}"
    assign_public_ip: yes
  register: instance

- name: Get Admin Password
  ec2_win_password:
    instance_id: "{{ instance.instances[0].id }}"
    region: "{{ region }}"
    key_file: "{{ playbook_dir }}/keypair.pem"
    wait: yes
  register: password

- debug: var=password

- name: Wait for WinRM
  win_wait_for:
    port: 5986

- add_host:
    name: "{{ instance.instances[0].public_dns_name }}"
    groups: just_created