---
# tasks file for instance_creation

- name: create new key pair
  ec2_key:
    name: keypair1
    region: "{{ region }}"
  register: key

- name: save pem file
  copy:
    content: "{{ key.key.private_key }}"
    dest: keypair.pem
    mode: 0400

- name: create vpc 
  ec2_vpc_net:
    name: myvpc
    state: present
    cidr_block: 10.10.0.0/16
    region: "{{ region }}"
  register: vpc

- name: create internet gateway
  ec2_vpc_igw:
    vpc_id: "{{ vpc.vpc.id }}"
    state: present
  register: igw

- name: subnet
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ region }}"
    cidr: 10.10.1.0/24
  with_items: vpc
  register: vpc_subnet

- name: ec2 security group
  ec2_group:
    name: "{{ group_name }}"
    description: security group for Mongo server
    region: "{{ region }}"
    vpc_id: "{{ vpc.vpc.id }}"
    rules: "{{ rules }}"
    rules_egress: "{{ rules_egress }}"

- ec2:
    key_name: keypair1
    region: "{{ region }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    wait: yes
    group: "{{ group_name }}"
    count: 1
    vpc_subnet_id: "subnet-05f6347305d7c187b"
    assign_public_ip: yes
  register: instance

- name: wait for ec2 instance
  wait_for:
    host: "{{ instance.instances[0].public_dns_name }}"
    port: 22
    state: started

- add_host:
    name: "{{ instance.instances[0].public_dns_name }}"
    groups: just_created
