---

  # - name: Provision an EC2 Instance
  #   hosts: localhost
  #   gather_facts: False
  #   tags: Provisioning

  #   roles:
  #     - instance_creation
  
  - name: Configure EC2
    hosts: all
    vars:
      ansible_ssh_private_key_file: "{{ playbook_dir }}/keypair.pem"
      ansible_ssh_user: ubuntu
      ansible_python_interpreter: /usr/bin/python3
    roles:
      -  configure_mongo