---
# tasks file for install_iis

#  - name: Install IIS
#    win_feature:
#     name:
#       - Web-Server
#       - Web-App-Dev
#       - Web-WMI
#       - Web-Common-HTTP
#       - Web-Security
#       - Web-Filtering
#       - Web-Static-Content
#       - Web-Default-Doc
#       - Web-Dir-Browsing
#       - Web-Http-Errors
#       - Web-Http-Redirect
#       - Web-ISAPI-Ext
#       - Web-ISAPI-Filter
#       - Web-Health
#       - Web-Http-Logging
#       - Web-Log-Libraries
#       - Web-Request-Monitor
#       - Web-Log-Libraries
#       - Web-Request-Monitor
#       - Web-Http-Tracing
#       - Web-Basic-Auth
#       - Web-Windows-Auth
#       - Web-Url-Auth
#       - Web-IP-Security
#       - Web-Performance
#       - Web-Stat-Compression
#       - Web-Dyn-Compression
#       - Web-Mgmt-Tools
#       - Web-Mgmt-Console
#       - RSAT-ADDS-Tools
#       - Web-Lgcy-Scripting
#       - Web-Scripting-Tools
#       - Web-Mgmt-Service
#       - Web-Mgmt-Compat
#       - Web-Metabase
#       - WAS
#       - File-Services
#       - FS-FileServer
#       - Telnet-Client

#     state: present

#  - name: Install WebDeploy
#    win_package:
#     path: "https://download.microsoft.com/download/0/1/D/01DC28EA-638C-4A22-A57B-4CEF97755C6C/WebDeploy_amd64_en-US.msi"
#     product_id: "6773A61D-755B-4F74-95CC-97920E45E696"
#     arguments: "ADDLOCAL=ALL"

#  - name: Create WebApp directory
#    win_file:
#     path: C:\WebApp
#     state: directory

#  - name: Download WebApp
#    win_get_url:
#     url: https://raw.githubusercontent.com/dannybritto96/Azure-Quickstart-Templates/master/WebDeploy/WebApplication1.zip
#     dest: C:\WebApp\WebApplication.zip


 - name: Start WebDeploy
   win_service:
    name: WMSVC
    start_mode: auto
    state: started
   register: temp

 - debug: var=temp 
 
 - name: Install WebApp
   win_shell: |
    $Argument = '-source:package="C:\WebApp\WebApplication.zip" -dest:auto,ComputerName="localhost", -verb:sync -allowUntrusted'
    $MSDeployPath = (Get-ChildItem "HKLM:\SOFTWARE\Microsoft\IIS Extensions\MSdeploy" | Select -Last 1).GetValue("InstallPath")
    Start-Process "$MSDeployPath\msdeploy.exe" $Argument -Verb runas
   register: psoutput

 - debug: var=psoutput